services:
  postgres:
    image: postgres:15-alpine
    container_name: de_postgres
    environment:
      - POSTGRES_USER=de_user
      - POSTGRES_PASSWORD=de_password
      - POSTGRES_DB=de_learning
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U de_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: